---

- hosts: all
  become: true
  tasks:

  - name: install nginx
    apt: name=nginx state=present
    sudo: yes

  - name: Error installing npm
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

  - name: update npm
    shell: npm i -g npm

  - name: Install apt npm
    apt: name=nodejs
  
  - name: Install express-graphql
    shell: npm install  express express-graphql graphql

  - name: Ensure bash latest versions
    apt: name=bash update_cache=true state=latest

  - name: Ensure OpenSSl latest versions
    apt: name=openssl update_cache=true state=latest

  - name: Ensure libssl latest versions
    apt: name=libpq-dev update_cache=true state=latest

  - name: Ensure python python-psycopg2 latest version
    apt: name=python-psycopg2 update_cache=true state=latest
  
  - name: Install postgreSQL
    npm: name=postgresql state=latest global=true

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes
  
  - name: Edit postgresql config file
    lineinfile: 
      dest: /etc/postgresql/9.5/main/pg_hba.conf
      regexp: "^hosts+all+192.168.17.133+127.0.0.1/32s+trust$"
      insertafter: "^#sIPv4slocal.+"
      line: "host    all             192.168.17.133  127.0.0.1/32            trust"

  - name: install rabbitMQ
    apt: name=rabbitmq-server  update_cache=true state=latest

  - name: enable mqtt on rabbitmq
    rabbitmq_plugin:
      names: rabbitmq_mqtt
      state: enabled
